### ISSUE TITLE
hostname resolution

### ISSUE THREAD

**Issue by bnebenda** [git-developer/autosuspend#15] opened 2020-05-07 06:21 UTC
The helper functions for the autosuspend script are using 

`hostname -I`

to resolve the hostname. I tested the script and on my machine this commands results is:

`192.168.178.41 2a02:8070:a185:2700:7285:c2ff:fef7:db57`

stripping whitespaces from this results in an invalid hostname, which leads to failed calls to the web interface of tvheadend. I replaced the call with

`hostname -i`

which returns

`127.0.1.1`

This works for me but maybe there is a reason not to do it this way. The documentation of hostname however also suggests not to rely on the order of the output of the ip addresses, so just using the first column might not work either.

**Comment by git-developer** [comment] 2020-05-07 06:46
Thanks fo your bug report.

In fact, the script started using `hostname -i`. If I remember correctly, Tvheadend was not bound to localhost (127.0.0.1) but only to an external IP (e.g. 192.168.x.y) on my machine. Thus I changed the default [as implemented now](https://github.com/git-developer/autosuspend/blob/023a4c31670b1527e3d10a1cfd2cf4e589292454/usr/local/sbin/autosuspend.tvheadend-functions#L31). Apparently, this implementation does not work when the machine has more than 1 external IP adress. I will check that.

You can workaround this issue by setting an explicit value for `TVHEADEND_IP` in your configuration file.

**Comment by bnebenda** [comment] 2020-05-07 07:16
Thanks for the hint. I used that workaround already but still changed the code. On my machine `hostname -i` returns `127.0.1.1` and not as you wrote `127.0.0.1`. 

`nslookup localhost` returns (as expected) `127.0.0.1`

The content of `/etc/hosts` on my machine is
`127.0.0.1 localhost
127.0.1.1 tvserver

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
`

**Comment by git-developer** [comment] 2020-05-07 17:23
Duplicate of #8 
After 2 years this fix should be merged into master...

**Comment by git-developer** [comment] 2020-05-07 18:11
The fix was merged into master ([a9dffe8](https://github.com/git-developer/autosuspend/commit/a9dffe8579434f902d3851fcf5ef43f67d4ac691)) and released as [2020-05-07](https://github.com/git-developer/autosuspend/releases/tag/2020-05-07).

**Closed by git-developer** 2020-05-07 18:11 UTC
